dist: trusty
sudo: required

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install g++-4.8 gcc -y -qq
  - make CXX=g++-4.8

install:
  - cd ebg; make && sudo make install

after_insall:
  - ebg -h
  - ebg hwe -h
  - ebg diseq -h
  - ebg alloSNP -h

notifications:
  email: false
