language: cpp
sudo: required

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install g++-4.8 gcc -y -qq

script:
  - cd ebg; make CXX=g++-4.8 && sudo make install

after_script:
  - ebg -h
  - ebg hwe -h
  - ebg diseq -h
  - ebg alloSNP -h

notifications:
  email: false
